#
## application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.


spring:
  datasource:

    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/Card_System

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8080

logging:
  level:
    org.hibernate.sql: debug

jwt:
  secret: KoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBWbmf0yVx59lDK33f093
  expiration: 86400000